dist: xenial
sudo: required
language: node_js
node_js:
  - "10"

services:
  - xvfb

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1200x24"
  - export CHROME_BIN=/usr/bin/google-chrome
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - google-chrome --version
  
before_script:
  # Rule server build
  - cd rule-server;
  - npm install;
  - npm run build;
  - cd dist;
  - node main.js &
  - sleep 10;   # Give server time to build and start
  - cd ..;
  - cd ..;

jobs:
  include:
    - stage: Tests
      name: accessibility-checker-engine
      script: travis/test/ace.sh
    - name: accessibility-checker - Selenium
      script: travis/test/achecker_selenium.sh
    - name: accessibility-checker - Other
      script: travis/test/achecker_other.sh
    - name: karma-accessibility-checker - Assert
      script: travis/test/karma_achecker_assert.sh
    - name: karma-accessibility-checker - Content
      script: travis/test/karma_achecker_content.sh
    - name: karma-accessibility-checker - Other
      script: travis/test/karma_achecker_other.sh
    - stage: Deploy
      name: Deploy rule server
      script: travis/publish/rules.sh
      if: branch = master OR branch = prod
    - name: Deploy accessibility-checker
      script: travis/publish/achecker.sh
      if: tag IS present AND branch = prod
    - name: Deploy karma-accessibility-checker
      script: travis/publish/karma-achecker.sh
      if: tag IS present AND branch = prod
    - name: Deploy accessibility-checker for Chrome
      script: travis/publish/achecker-chrome.sh
      if: tag IS present AND branch = prod
    - name: Deploy accessibility-checker for Firefox
      script: travis/publish/achecker-firefox.sh
      if: tag IS present AND branch = prod
