# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Extension Build

on:
  push:
    branches: '*'

jobs:
  accessibility-checker-engine-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: accessibility-checker-engine
    - run: npx karma start --single-run --watch=false
      working-directory: accessibility-checker-engine

  accessibility-checker-test-basic:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [12.x]

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: accessibility-checker-engine
      - run: npm run build
        working-directory: accessibility-checker-engine
      - run: ls 
        working-directory: accessibility-checker-engine/dist
      - run: npm install
        working-directory: accessibility-checker
      - run: npx mocha -R dot test/mocha/aChecker.Fast/**/*.test.js
        working-directory: accessibility-checker

  extension-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: report-react
    - run: npm install
      working-directory: accessibility-checker-extension
    - run: npm run package:browser
      working-directory: accessibility-checker-extension

  extension-build:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'
    needs: extension-test

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: report-react
    - run: npm install
      working-directory: accessibility-checker-extension
    - run: npm run package:browser
      working-directory: accessibility-checker-extension
    - name: Upload packed extension
      uses: actions/upload-artifact@v1
      with:
        name: accessibility-checker-extension
        path: accessibility-checker-extension/package/accessibility-checker-extension.zip
