# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release publish

on:
  push:
    branches: 
      - workflow-test

jobs:
###############################################################################
# NPM Node
####
  cypress-accessibility-checker-publish:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [12.x]

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: cypress-accessibility-checker
      - run: npm run build:report
        working-directory: cypress-accessibility-checker
      - run: npm run package:npm
        working-directory: cypress-accessibility-checker
      - run: gitactions/publish/cypress-achecker.sh
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  extension-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: report-react
    - run: npm install
      working-directory: accessibility-checker-extension
    - run: cp -f ./manifest_Chrome.json ./src/manifest.json
      working-directory: accessibility-checker-extension
    - run: |
        if [[ -n "${GITHUB_REF:10}" ]]; then 
          RELEASE_VERSION=${GITHUB_REF#refs/*/} && sed -i'.old' -e 's/"version": "3.0.0"/"version": "'"${RELEASE_VERSION}"'"/g' ./manifest.json
        fi;
      working-directory: accessibility-checker-extension/src
    - run: rm manifest.json.old
      working-directory: accessibility-checker-extension/src
    - run: npm run package:browser
      working-directory: accessibility-checker-extension
    - name: Upload packed extension
      uses: actions/upload-artifact@v1
      with:
        name: accessibility-checker-extension for Chrome
        path: accessibility-checker-extension/package/accessibility-checker-extension.zip
    - run: cp -f ./manifest_Firefox.json ./src/manifest.json
      working-directory: accessibility-checker-extension
    - run: |
        if [[ -n "${GITHUB_REF:10}" ]]; then 
          RELEASE_VERSION=${GITHUB_REF#refs/*/} && sed -i'.old' -e 's/"version": "3.0.0"/"version": "'"${RELEASE_VERSION}"'"/g' ./manifest.json
        fi;
      working-directory: accessibility-checker-extension/src
    - run: rm manifest.json.old
      working-directory: accessibility-checker-extension/src
    - run: npm run package:browser
      working-directory: accessibility-checker-extension
    - name: Upload packed extension
      uses: actions/upload-artifact@v1
      with:
        name: accessibility-checker-extension for Firefox
        path: accessibility-checker-extension/package/accessibility-checker-extension.zip
